# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
# Find more information on toml format here:  https://github.com/toml-lang/toml
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
# Side this dependency is applied on - BOTH, CLIENT, or SERVER

modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_authors}"
displayTest = "MATCH_VERSION"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "farmersdelight"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="iceandfire"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="mynethersdelight"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="collectorsreap"
mandatory=false
versionRange="[1.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="brewinandchewin"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"